# Generated by cpputils-cmake.
include /Users/ikarino/Dropbox/GSCS/scs/build/CMakeFiles/scs.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} -I/usr/src/linux/include -DNDEBUG -S ${CHK_SOURCES}